variables:
  GIT_SUBMODULE_STRATEGY: recursive

stages:
  - test_linux
  - test_android
  - appimage

Test_linux:
  stage: test_linux
  image:
    name: "carlonluca/qt-dev:6.9.2"
    entrypoint: [""]
  script:
    - mkdir build
    - cd build
    - qt-cmake ..
    - make

Test_android:
  stage: test_android
  image:
    name: "carlonluca/qt-dev:6.9.2"
    entrypoint: [""]
  script:
    - mkdir build
    - cd build
    - /opt/qt/6.9.2/android_armv7/bin/qt-cmake ..
    - make
    - test -f ./android-build/build/outputs/apk/debug/android-build-debug.apk

Appimage:
  stage: appimage
  image:
    name: "carlonluca/qt-dev:6.9.2"
    entrypoint: [""]
  script:
    - qt-cmake . -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX=/usr
    - cmake --build .
    - make install DESTDIR=AppDir
    - mkdir -p AppDir/usr/share/icons
    - touch AppDir/usr/share/icons/icon.png
    - . /venv/bin/activate
    - appimage-builder --recipe appimage/AppImageBuilder.yml
  artifacts:
    paths:
      - Fall-latest-x86_64.AppImage
